<?php

namespace App\Helpers;

class City
{
    protected $cities;

    public function __construct()
    {
        $this->cities = [
            ['name' => 'Alingsås'],
            ['name' => 'Arboga'],
            ['name' => 'Arvika'],
            ['name' => 'Askersund'],
            ['name' => 'Avaskär'],
            ['name' => 'Avesta'],
            ['name' => 'Boden'],
            ['name' => 'Bollnäs'],
            ['name' => 'Borgholm'],
            ['name' => 'Borlänge'],
            ['name' => 'Borås'],
            ['name' => 'Broo'],
            ['name' => 'Brätte'],
            ['name' => 'Båstad'],
            ['name' => 'Djursholm'],
            ['name' => 'Eksjö'],
            ['name' => 'Elleholm'],
            ['name' => 'Enköping'],
            ['name' => 'Eskilstuna'],
            ['name' => 'Eslöv'],
            ['name' => 'Fagersta'],
            ['name' => 'Falkenberg'],
            ['name' => 'Falköping'],
            ['name' => 'Falsterbo'],
            ['name' => 'Falun'],
            ['name' => 'Filipstad'],
            ['name' => 'Flen'],
            ['name' => 'Gamla Lödöse'],
            ['name' => 'Getakärr'],
            ['name' => 'Gränna'],
            ['name' => 'Gåsekil'],
            ['name' => 'Gävle'],
            ['name' => 'Göteborg'],
            ['name' => 'Hagfors'],
            ['name' => 'Halmstad'],
            ['name' => 'Haparanda'],
            ['name' => 'Hedemora'],
            ['name' => 'Helsingborg'],
            ['name' => 'Hjo'],
            ['name' => 'Hudiksvall'],
            ['name' => 'Huskvarna'],
            ['name' => 'Härnösand'],
            ['name' => 'Hässleholm'],
            ['name' => 'Hästholmen'],
            ['name' => 'Höganäs'],
            ['name' => 'Järle'],
            ['name' => 'Jönköping'],
            ['name' => 'Kalmar'],
            ['name' => 'Karl Johans stad'],
            ['name' => 'Karlshamn'],
            ['name' => 'Karlskoga'],
            ['name' => 'Karlskrona'],
            ['name' => 'Karlstad'],
            ['name' => 'Katrineholm'],
            ['name' => 'Kiruna'],
            ['name' => 'Kongahälla'],
            ['name' => 'Kramfors'],
            ['name' => 'Kristianopel'],
            ['name' => 'Kristianstad'],
            ['name' => 'Kristinehamn'],
            ['name' => 'Kumla'],
            ['name' => 'Kungsbacka'],
            ['name' => 'Kungälv'],
            ['name' => 'Köping'],
            ['name' => 'Laholm'],
            ['name' => 'Landskrona'],
            ['name' => 'Lidingö'],
            ['name' => 'Lidköping'],
            ['name' => 'Lindesberg'],
            ['name' => 'Linköping'],
            ['name' => 'Ljungby'],
            ['name' => 'Lomma'],
            ['name' => 'Ludvika'],
            ['name' => 'Luleå'],
            ['name' => 'Lund'],
            ['name' => 'Luntertun'],
            ['name' => 'Lycksele'],
            ['name' => 'Lyckå'],
            ['name' => 'Lysekil'],
            ['name' => 'Lödöse'],
            ['name' => 'Malmö'],
            ['name' => 'Mariefred'],
            ['name' => 'Mariestad'],
            ['name' => 'Marstrand'],
            ['name' => 'Mjölby'],
            ['name' => 'Motala'],
            ['name' => 'Mönsterås'],
            ['name' => 'Nacka'],
            ['name' => 'Nora'],
            ['name' => 'Norrköping'],
            ['name' => 'Norrtälje'],
            ['name' => 'Nya Lidköping'],
            ['name' => 'Nya Lödöse'],
            ['name' => 'Ny Varberg'],
            ['name' => 'Nybro'],
            ['name' => 'Nyköping'],
            ['name' => 'Nynäshamn'],
            ['name' => 'Nässjö'],
            ['name' => 'Oskarshamn'],
            ['name' => 'Oxelösund'],
            ['name' => 'Piteå'],
            ['name' => 'Ronneby'],
            ['name' => 'Sala'],
            ['name' => 'Sandviken'],
            ['name' => 'Sigtuna'],
            ['name' => 'Simrishamn'],
            ['name' => 'Skanör'],
            ['name' => 'Skanör med Falsterbo'],
            ['name' => 'Skara'],
            ['name' => 'Skellefteå'],
            ['name' => 'Skänninge'],
            ['name' => 'Skövde'],
            ['name' => 'Sollefteå'],
            ['name' => 'Solna'],
            ['name' => 'Stockholm'],
            ['name' => 'Strängnäs'],
            ['name' => 'Strömstad'],
            ['name' => 'Stäket'],
            ['name' => 'Sundbyberg'],
            ['name' => 'Sundsvall'],
            ['name' => 'Säffle'],
            ['name' => 'Säter'],
            ['name' => 'Sävsjö'],
            ['name' => 'Söderhamn'],
            ['name' => 'Söderköping'],
            ['name' => 'Södertälje'],
            ['name' => 'Sölvesborg'],
            ['name' => 'Tidaholm'],
            ['name' => 'Torget'],
            ['name' => 'Torshälla'],
            ['name' => 'Tranås'],
            ['name' => 'Trelleborg'],
            ['name' => 'Trollhättan'],
            ['name' => 'Trosa'],
            ['name' => 'Tumathorp'],
            ['name' => 'Uddevalla'],
            ['name' => 'Ulricehamn'],
            ['name' => 'Umeå'],
            ['name' => 'Uppsala'],
            ['name' => 'Vadstena'],
            ['name' => 'Varberg'],
            ['name' => 'Vaxholm'],
            ['name' => 'Vetlanda'],
            ['name' => 'Vimmerby'],
            ['name' => 'Visby'],
            ['name' => 'Vä'],
            ['name' => 'Vänersborg'],
            ['name' => 'Värnamo'],
            ['name' => 'Västervik'],
            ['name' => 'Västerås'],
            ['name' => 'Växjö'],
            ['name' => 'Ystad'],
            ['name' => 'Åhus'],
            ['name' => 'Åmål'],
            ['name' => 'Älvsborg'],
            ['name' => 'Ängelholm'],
            ['name' => 'Örebro'],
            ['name' => 'Öregrund'],
            ['name' => 'Örnsköldsvik'],
            ['name' => 'Östersund'],
            ['name' => 'Östhammar'],
        ];
    }

    public function getAllCities(): array
    {
        return $this->cities;
    }
}
